AWSTemplateFormatVersion: '2010-09-09'
Description: "Deploy EC2, S3, and RDS using CloudFormation"

Resources:

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-cloudformation-s3-bucket-vishwaraj-0413  # Replace with your S3 Bucket name

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-080b1a55a0ad28c02  # Amazon Linux 2 AMI (check for your region)
      InstanceType: t2.micro
      KeyName: test-key       # Replace with your EC2 key pair name
      SecurityGroups:
       - default

  MyRDSInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBInstanceIdentifier: mydbinstance
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MTSQL
      MasterUsername: adminuser
      MasterUserPassword: mysecurepassword
      PubliclyAccessible: true